import Admin_Navbar from "@/components/admin/Admin_Navbar";
import { Geist, Geist_Mono } from "next/font/google";
// import Admin_Navbar from "@/components/admin/Admin_Navbar";
import '../../globals.css'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex gap-x-4">
        <div className="w-[20vw]">
        <Admin_Navbar/>
        </div>
        <div className="w-[80vw] border h-full">
        {children}
        </div>
        </div>
      </body>
    </html>
  );
}
