import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/user/Navbar";
// import Filter from "@/components/user/HomePage/Filter";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f0f0f0]`}
      >
        <div className="gap-x-4">
        <Navbar/>
        <div className="flex ">
          {/* <Filter/> */}
        {children}
        </div>
        </div>
      </body>
    </html>
  );
}
